### ISSUE TITLE
如果获取锁后,执行的时间超过了设定的拥有锁的时间该怎么办?

### ISSUE THREAD

**Issue by wjw465150** [baomidou/lock4j#2]
如果获取锁后,执行的时间超过了设定的拥有锁的时间该怎么办?

**Comment by pengpan** [comment]
过期时间一定是要长于业务的执行时间. 
等作者改进吧 @baomidou

**Comment by zengzhihong** [comment]
如果使用RedissonExecutor会自动续期

**Comment by zengzhihong** [comment]
2.2.5 redisTemplate已支持锁续期
