### ISSUE TITLE
关于redisson锁自动续期的问题

### ISSUE THREAD

**Issue by telechow** [baomidou/lock4j#4]
# Enviroment

JDK Version: 
1.8
SpringBoot Version: 
2.3.16
Lock4j Version: 
2.2.2

# Describe
![image](https://user-images.githubusercontent.com/9656433/160075887-080a9971-a23c-4e4f-beb3-9b74dd8c1d43.png)
如图，这个是lock4j的源码截图，上面写着使用redisson且expire为-1就会自动续期锁。

Expected Result: 
但是实际上并不会，看我给大家分析一下
 
Actual Result:  
实际上即使使用了redisson且配置expire为-1，锁还是会在一定时间过期不会再续期；
为什么？请往下看
# Steps to reproduce
- Step 1 
![image](https://user-images.githubusercontent.com/9656433/160076372-e09ced42-043c-49e1-9ac9-df12bf4d9849.png)
LockTemplate中读取参数，如果如果使用了redisson且设置了expire为-1，很自然得到了过期时间为-1
这里没有问题
![image](https://user-images.githubusercontent.com/9656433/160076700-deeccf7b-64ca-40c6-9466-35c7592c3b35.png)
然后小面调用了锁执行器接口的实现类的acquire方法，将上面的-1传进去了
这里也没有问题

- Step 2 
![image](https://user-images.githubusercontent.com/9656433/160077174-55a12132-c843-4252-8c9c-3138adf295a7.png)
在redisson的锁执行器中，创建了一个RLock，然后调用RLock的tryLock方法将expire为-1传了进去
这里也没有问题
![image](https://user-images.githubusercontent.com/9656433/160077534-005ceebd-e5ef-4fb9-8089-47c66f135280.png)
传进来后，在redisson的RedissonLock类的此方法中，expire的值-1被赋给了leaseTime
然后调用了tryAcquire方法
这里也没有问题

- Step 3 
![image](https://user-images.githubusercontent.com/9656433/160078074-6dffbd1a-4418-4cc6-99bc-8c0045986d47.png)
最后走到这里，如果leaseTime值为-1，tryLockInnerAsync方法就会传一个配置里面的值作为leaseTime
问题来了，LockWatchdogTimeout是什么意思？
[https://github.com/redisson/redisson/wiki/2.-%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95#lockwatchdogtimeout%E7%9B%91%E6%8E%A7%E9%94%81%E7%9A%84%E7%9C%8B%E9%97%A8%E7%8B%97%E8%B6%85%E6%97%B6%E5%8D%95%E4%BD%8D%E6%AF%AB%E7%A7%92](url)
```
lockWatchdogTimeout（监控锁的看门狗超时，单位：毫秒）
默认值：30000

监控锁的看门狗超时时间单位为毫秒。该参数只适用于分布式锁的加锁请求中未明确使用leaseTimeout参数的情况。如果该看门口未使用lockWatchdogTimeout去重新调整一个分布式锁的lockWatchdogTimeout超时，那么这个锁将变为失效状态。这个参数可以用来避免由Redisson客户端节点宕机或其他原因造成死锁的情况。
```

原来是这个意思。

那么redisson也不是无限期的为我们续期锁，而是在这个默认30秒的时间内给我们自动续期锁。
这个和lock4j配置的默认值expire为30000毫秒，在实际使用上有什么区别呢？
没有区别吧。redis中的key还是会在30秒后消失。

你可以改LockWatchdogTimeout的值，改大一点，但是这没有意义，同样可以把lock4j的expire值改大一点。

这就是redisson锁自动续期的问题了。代码写的很好很规范，就是绕了一圈又绕回来了。

@baomidou   @zengzhihong   

最后，lock4j很好用，我们庙里面就在用这个项目做分布式锁。代码写的也很规范，我都拿给实习生学习。因为这个项目小且有用。
期待baomidou做出更多更好的开源产品。

**Comment by tanpenggood** [comment]
我们现在加锁的最佳实践是：
```java
    @Lock4j(keys = {"'pay'", "#amount"},
            expire = -1, // -1代表根据业务方法执行时间自动续期
            autoRelease = true, // 业务方法执行结束自动释放锁
            executor = RedissonLockExecutor.class,
            failStrategy = CustomLockFailureStrategy.class)
    void autoRenewAndAutoReleaseLock(BigDecimal amount);
```

## Enviroment

- JDK Version: 1.8
- SpringBoot Version: 2.6.8
- Lock4j Version: 2.2.7
